### ISSUE TITLE
#1: User can view their list of streamers

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/final-project-stream-team#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able view a list of all streamers they have added to their list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the home page loads, the user will be able to see a list of their followed streamers.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/73370554/129301139-0237a25e-2c87-4798-8ef0-4dd042f935cf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create initial database
- [x] Update `data.sql` to create a dummy user and streamer profiles

### ☁️ Server

- [x] Add `GET /api/likes` endpoint to get all of a users followed/liked streamer profiles
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create Home Component
- [x] Make `fetch` request in `componentDidMount` of App component to `GET /api/likes`
- [x] Update state with streamer data
- [x] Display streamer data in home page
- [x] Style the page
   - [x] Header
      - [x] Desktop
      - [x] Mobile
   - [x] Subheader
      - [x] Desktop
      - [x] Mobile
   - [x] Body
      - [x] Desktop
      - [x] Mobile
   - [x] Streamer Profile
      - [x] Desktop
      - [x] Mobile

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
