### ISSUE TITLE
#8: User can remove a streamer

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/final-project-stream-team#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to remove a profile they are following from their list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to send a `DELETE` request to `/api/likes/:userId/:streamerId`
   - [x] If the profile is also in the users `favorites` (tested on client side), send a DELETE` request to `/api/favorites/:userId/:streamerId`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update "Large Profile" component to:
- [x] Add an `onClick` event listener to the `fa-trash` icon
   - [x] In the event listener callback, display a confirmation modal box for the user to confirm if they want to delete this user
- [x] Add an `onClick` event listener to the `Yes` button in the confirmation modal
   - [x] In the event callback, use `fetch` to send the `DELETE` request(s) created in the "Server" section
   - [x] If the response is okay, re-render the page with the current streamers
- [x] Add an `onClick` event listener to the `No` button in the confirmation modal
   - [x] In the event callback, hide the confirmation modal
- [x] Add an `onClick` event listener to the `x` icon in the confirmation modal
   - [x] In the event callback, hide the confirmation modal

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
