### ISSUE TITLE
#2: User can add a streamer to their "Favorites"

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/Final-Project-Stream-Team#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add a streamer profile to their `favorites`.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon clicking the `star` icon in the bottom of a streamer's profile, that streamer will be added to the users `favorites`, which sorts that profile to the top of their list of followed streamers. The `star` icon will then display as solid.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/73370554/129302441-bf03f0b8-f114-4c6a-9719-517c658178ae.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `data.sql` to add the `userId` of the user that added the favorite and the `streamerId` of the targeted favorite into a table labeled `favorites`

### ☁️ Server

- [ ] Update `server/index.js` to add a `POST /api/favorites/` route to add a streamer to a user's favorites
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update `star` component to handle `click` event
   - [ ] To send the `POST` route and
   - [ ] Update the `star` to display a solid version instead
- [ ] Update `state` with the streamer data (that is, some `favorite` property now set to `true`
- [ ] Display updated/reordered streamer data in home page

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
