### ISSUE TITLE
#3: User can remove a favorite

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/final-project-stream-team#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to remove a streamer profile from their `favorites`

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon clicking a solid `star` icon in the bottom of a streamer's profile, that streamer will be removed from the users `favorites`, which will bump the profile to be sorted after `favorites`. The `star` icon will then display as empty again.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/73370554/129302441-bf03f0b8-f114-4c6a-9719-517c658178ae.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to remove the row from the `favorites` table that includes the appropriate user's `userId` and the targeted streamer's `streamerId`

### ☁️ Server

- [x] Update `server/index.js` to add a `DELETE /api/favorites/` route to remove a streamer from a user's `favorites`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `star` element of `smallProfile` component's `click` handler to:
   - [x] Send the `DELETE` route 
   - [x] Provide visual feedback on click (color)
   - [x] Update the `star` to display an empty version instead
- [x] Update `state`
- [x] Display updated/reordered streamer data in home page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
