### ISSUE TITLE
#4: User can view a streamer’s profile

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/final-project-stream-team#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a large profile with additional information for each streamer

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking specific streamer's `display name` or `profile image` will create a popup modal to display a larger streamer profile (in particular, their profile's description will be available to read)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/73370554/131443352-cece8b4e-9892-4858-bbc6-7ba593d508bd.png)

![image](https://user-images.githubusercontent.com/73370554/131443408-865c2acc-0c5f-4f07-84d0-1f2404667c83.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to display a popup modal container for an expanded streamer profile
- [x] Design component to be reusable (ie, for different popup modal functions)
- [x] Update component to display a selected streamer's data
- [x] Style the component
   - [x] Fonts
   - [x] Colors
   - [x] Spacing
   - [x] Breakpoints
- [x] Add `click` event listener to the small streamer profiles (in particular, the `display name` and `profile image` elements)
   - [x] On click, display the specific streamers larger profile, rendering extra data that can't be fit on the small profiles in the list
- [x] Add `click` event listener to the popup modal
   - [x] Check for click on the `x` icon or on the shaded background (outside of the modal container itself)
   - [x] Close the modal container if the above criteria is satisfied

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
