### ISSUE TITLE
#9: User can view current information

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/final-project-stream-team#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view current profile information for their followed streamers

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the page loads, the most current profile data will be displayed to the user. API requests to YouTube and Twitch will be periodically sent to ensure data on this app is up to date.

To avoid quota issues, API requests for current video uploads will be sent every 2 hours, and API requests for current profile information will be sent every 12 hours.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include `videoUpdated` column to determine the last time the video URL was updated

### ☁️ Server

- [x] Update `server/index.js` to:
   - [x] Retrieve all saved streamer profiles, and check the `lastUpdated` column
   - [x] For each entry, if `lastUpdated` is greater than 24 hours, send a `GET` request to get the current profile information: 
      - [x] Twitch request
      - [x] YouTube request
      - [x] If the response is okay, update the `streamers` table with the updated profile information (display name, description, image)
   - [x] For each entry, if `videoUpdated` is greater than 2 hours old, send a `GET` request to get the most recent video URL
      - [x] Twitch request
      - [x] YouTube request
      - [x] If the response is okay, update the `streamers` table with the updated video URL & current video upload time
   - [x] Update the `get` route to download profile images to the server, saving the filenames as `channelId`
   - [x] Update the `put` route to download new profile images to the server, saving the filenames as `channelId`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update App.js component to:
   - [x] Send a `put` request to check for current profile data in `componentDidMount`, & call the `retrieveData` method after it is completed
   - [x] Periodically send a `put` request for profile information (`setInterval`) & call the `retrieveData` method after it is completed
   - [x] Send a `put` request to check for current video data in `componentDidMount`, & call the `retrieveData` method after it is completed
   - [x] Periodically send a `put` request for current video urls (`setInterval`) & call the `retrieveData` method after it is completed
- [x] Update `small-profile.jsx` and `large-profile.jsx` to get local image URLs instead of using external urls.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
