### ISSUE TITLE
#5: User can search for a streamer

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/final-project-stream-team#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to search for streamers by `displayName`.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will type a name in the search bar, and it will dynamically update with any streamers whose `displayName` includes the typed string.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/73370554/131940526-e20790e4-13c1-400c-8056-c8f7858496e4.png)

![image](https://user-images.githubusercontent.com/73370554/131940558-0d54cbd2-217a-4c7a-87d6-fe34a8a9eaa3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a handleChange method on the `App` component to parse the string that is typed
- [x] Modify the `form` element in the `Subheader` component to add event handler and form control 
   - [x] Modify state with search information
   - [x] Update state with typed information
- [x] Conditionally render all profiles who match the typed string

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
