### ISSUE TITLE
#7: User can add a streamer (Youtube)

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/final-project-stream-team#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add a new YouTube profile to their list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The popup modal to add a profile to follow will accept YouTube channel URLs as well. The YouTube channel's information will be retrieved, and the user can then confirm that they wish to add the profile to their list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/73370554/132145525-ef4f641a-6a81-4040-a854-de18ac4bc1b5.png)

![image](https://user-images.githubusercontent.com/73370554/132145536-c587f496-35df-4d25-9427-45f849bdac15.png)

![image](https://user-images.githubusercontent.com/73370554/132145560-3f27b775-bdba-403f-9269-09ed41434ac0.png)

![image](https://user-images.githubusercontent.com/73370554/132145569-2ea1911e-52c5-41b3-8619-5e67a5ca3ed9.png)

#### Error State (will explore more detailed messages in the actual app):
![image](https://user-images.githubusercontent.com/73370554/132145590-929868de-7329-4c8d-a8dd-9cc267818d36.png)

#### Selecting "No" after a profile is retrieved (re-routes to the entry field):
![image](https://user-images.githubusercontent.com/73370554/132145617-2a0d94bb-dc6f-4113-b173-1f654901a0e6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to:
- [x] Modify the `GET` request to the `streamers` table: 
- [x] After checking if the `channelId` is in the `streamers` table, if response is empty, modify the `GET` `fetch` request to send the request to either Twitch.tv or YouTube (depending on information passed through) to get a user's profile
   - [x] If response from YouTube is `200` and data is retrieved:
     - [x] `Insert` the response data into the `streamers` table to add the streamer's profile
   - [x] Then, send a separate `GET` `fetch` request to YouTube to get a user's most recent video url
     - [x] `Update` the recentVideo in the `streamers` table with the response
     - [x] Respond with the streamer's profile data (for the confirmation screen)
- [x] Separately, send a `POST` request to the `likes` table, containing the `streamerId`, and the `userId` of the user who added the streamer.
   - [x] If postgres error code `23505` is returned, throw a new `clientError` with status code `400`, stating that the user is already following this profile
   - [x] If no error is returned, the `streamerId` and `userId` will be added to the user's likes and a `201` response will be received
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the `App` component: 
   - [x] Update the `addProfileValidator` method to validate YouTube URLs as well
   - [x] Update the `addProfileSubmit` method to parse the YouTube channel's URL to obtain the channel's id from the URL
      - [x] Update the `fetch` request to send information determining if the URL is Twitch or YouTube.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
