### ISSUE TITLE
#6: User can add a streamer (Twitch)

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/final-project-stream-team#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add a new twitch profile to their list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click the `bars` icon, which will reveal a dropdown modal list, with one of the options being 'Add a Streamer'. User will click this link, revealing a popup modal with a textbox input that accepts a Twitch.tv url.

Upon pasting and submitting the desired Twitch URL, a loading image will be displayed while the profile's data is retrieved. Upon retrieval, the profile image and display name will be shown, along with a confirmation dialog to determine if the correct profile was retrieved. If the user clicks `yes`, the streamer profile will be added to the user's profile list and their `likes` database.

Failed retrievals and cancellation requests will also be handled.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to change name of `twitchLogin` to `twitchId` which is an internal id sometimes utilized in the Twitch API 
- [x] Update `data.sql` to standardize `channelId`; `twitchLogin`'s value will be placed here, instead.

### ☁️ Server

- [x] Update `server/index.js` to:
- [x] Send a `GET` request to the `streamers` table to determine if the profile's data is already saved
   - [x] If so, respond with the profile's data (for use in the confirmation screen)
- [x] If response is empty, `index.js` will send a `GET` `fetch` request to Twitch.tv to get a user's profile
   - [x] If response from Twitch is `200` and data is retrieved:
     - [x] `Insert` the response data into the `streamers` table to add the streamer's profile
   - [x] Then, send a separate `GET` `fetch` request to Twitch.tv to get a user's most recent video url
     - [x] `Update` the recentVideo in the `streamers` table to the repsonse
     - [x] Respond with the streamer's profile data (for the confirmation screen)
- [x] Separately, send a `POST` request to the `likes` table, containing the `streamerId`, and the `userId` of the user who added the streamer.
   - [x] If postgres error code `23505` is returned, throw a new `clientError` with status code `400`, stating that the user is already following this profile
   - [x] If no error is returned, the `streamerId` and `userId` will be added to the user's likes and a `201` response will be received
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display the dropdown menu from the bars icon
   - [x] Add links in the dropdown
   - [x] Style with CSS
      - [x] Breakpoints
      - [x] Fonts
      - [x] Colors
      - [x] Positioning
- [x] Update `bars` icon in the `Header` to listen for a `click` event
- [x] In the event callback, make the page display a dropdown menu
- [x] If the "Add a profile" link is clicked, display a popup modal with a textbox form & submit button
- [x] Style the modal container:
   - [x] Positioning
   - [x] Colors
   - [x] Fonts
   - [x] Breakpoints
- [x] Add an onChange event listener to the textbox form which will:
   - [x] Parse the text entered and reject a bad url (ie, non-Twitch/bad formatting)
   - [x] Change the submit button to be clickable once the text appears to be valid
- [x] Add an onSubmit event listener to the textbox form which will:
   - [x] Send a `fetch` request to `GET /api/streamers/:channelId`, with `channelId` being parsed from the text entered
   - [x] If the status is a bad request, display an error message on the page and ask the user if they would like to try again
- [x] While the `fetch` request is awaiting a response, render a loading message in the "add streamer" modal box
- [x] If the profile was in the `fetch` request to `GET /api/streamers/:channelId` OR the data was added to the profiles after receiving the data from the Twitch API, and the response was `200`:
   - [x] Render the `displayName` and `profileImg` in the modal and ask user if the profile displayed is correct.
      - [x] If the user clicks the `Yes` button, send a `fetch` request to `POST /api/likes/:userId/:streamerId` to add the profile to the list of followed streamers
         - [x] If an error is thrown, with PostgreSQL error code `23505`, display the `ClientError` that was thrown as indicated in the Server tasks above
      - [x] call the `retrieveData` method in `app.jsx`. Process ends here
      - [x] If the user clicks the `No` button, change the display in the modal box back to the entry form

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
